config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :items

  get '/cart', to: 'orders#cart'
  post '/orders', to: 'orders#create', as: 'new_order'
  post 'checkout', to: 'orders#checkout', as: 'checkout'
  resources :orders
  delete '/orders', to: 'orders#destroy', as: 'remove_item'

  post '/login', to: 'sessions#create', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :order_items
  has_many :orders, through: :order_items
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items
  has_many :items, through: :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :item

  def self.total_due(order_id)
    amount_due = 0
    items_from_table = OrderItem.select('*').where(order_id: order_id)
    items_from_table.each do|item|
      amount_due += (item.item.cost * item.quantity) if item.item
    end
    amount_due
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :orders, dependent: :destroy
  has_many :items, through: :orders, dependent: :destroy
  validates_presence_of :email, :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authenticate_user!
     if session[:user_id] == nil
      flash[:alert] = "You must be logged in to do that."
      return false
    end
    true
  end

  def current_user_an_admin?(user)
    if user[:admin]
      true
    else
      false
    end
  end

  helper_method :current_user_an_admin?

  def new_user
    @new_user = User.new
  end

  helper_method :new_user

  def get_cart
    if authenticate_user!
      @user_order = Order.find_by(user_id: session[:user_id], completed: false)
    else
      redirect_to root_path, notice: "Please log in"
    end
  end

  helper_method :get_cart
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all.paginate(:page => params[:page], :per_page => 15)
  end

  def show
    begin
      @item = Item.find(params[:id])
    rescue ActiveRecord::RecordNotFound => error
      redirect_to :back, flash[:alert] = 'Record not Found', status: 404
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    if authenticate_user!
      user = User.find(session[:user_id])
      if current_user_an_admin?(user)
        @orders = Order.all.paginate(:page => params[:page], :per_page => 15)
      else
        redirect_to :back, flash[:alert] = "Access Denied"
      end
    else
      redirect_to root_path, flast[:alert] = "Please log In"
    end
  end

  def show
    if authenticate_user!
      @order = Order.find(params[:id])
    else
      redirect_to root_path, alert: "Please log In"
    end
  end

  def cart
    if authenticate_user!
      @user_order = Order.find_by(user_id: session[:user_id], completed: false)
    else
      redirect_to root_path, notice: "Please log in"
    end
  end

  def checkout
    if authenticate_user!
      @user = User.find(session[:user_id])
      @user_order = Order.find_by(user_id: @user.id, completed: false)
      @items = @user_order.order_items
      @total_paid = @user_order.order_items.total_due(@user_order[:id])
      @user_order[:completed] = true
      if @user_order.save
        CheckoutCompleted.checkout_confirmation(@user, @user_order).deliver_now
        redirect_to root_path, notice: "Your order has been processed"
      else
        redirect_to :back, alert: "Error processing checkout"
      end
    else
      redirect_to root_path, notice: "Please log in"
    end
  end

  def create
    if authenticate_user!
      @order = Order.find_or_create_by(user_id: session[:user_id], completed: false)
      @order.save

      @order_item = OrderItem.find_or_create_by(order_id: @order.id, item_id: params[:item_id])
      @order_item[:quantity] += params[:quantity].to_i

      if @order_item.save
        redirect_to :back, notice: "This item has been added to your cart"
        # redirect_to root_path, notice: "Your item has been added to your cart"
      else
        render :new, flash[:alert] = "Item was not saved, make sure you're logged in"
      end
     else
       redirect_to root_path
    end
  end

  def destroy
    if authenticate_user!
      user = User.find(session[:user_id])
      open_order = Order.find_by(user_id: user.id, completed: false)
      open_order.order_items
      order = OrderItem.find_by(order_id: open_order.id, item_id: params[:id])
      order.destroy!
      redirect_to :back, notice: "Item has been removed"
    else
      redirect_to root_path, alert: "Please log in"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create

  user = User.find_by_email(params[:email])
  if user.authenticate(params[:password])
    session[:user_id] = user.id
    redirect_to root_path, notice: "Welcome, #{user.name}"
  else
    flash[:alert] = "Password did not match records"
    render :new
  end
end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Thank for stopping by!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    # user = User.find(session[:user_id])
    # if current_user_an_admin?(user)
      @users = User.all#.paginate(:page => params[:page], :per_page => 30)
    # end
  end

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "Welcome #{@user.name.capitalize}"
    else
      flash[:alert] = "Error Occured"
    end
  end

  def show
    authenticate_user!
    begin
      if current_user.id == session[:user_id]
        @user = User.find(session[:user_id])
      end
    rescue ActiveRecord::RecordNotFound
      redirect_to :back, flash[:alert] = "Record not found"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/checkout_completed/checkout_confirmation.html.erb
Hello <%= @user.name %>

<p>Your order #<%= @order.id%>, has processed.</p>
<% @items.each do |item| %>
    <ul>
      <li><%= item.inspect %></li>
      <ul><li><%= number_to_currency(item[:cost]) %></li></ul>
    </ul>
<% end %>
<p>Total Paid: <%= number_to_currency(@total_paid) %></p>
<p>Thank you for your business!</p>

app/views/checkout_completed/checkout_confirmation.text.erb
Hello <%= @user.name %>

Your order #<%= @order.id%>, has processed.
<% @items.each do |item| %>

     <%= item.inspect %>
     <%= number_to_currency(item[:cost]) %>

<% end %>
Total Paid: <%= number_to_currency(@total_paid) %>
Thank you for your business!

app/views/items/index.html.erb
 <table class="table table-hover for-yield">
    <thead>
     <tr>
       <th>Item</th>
       <th>Price</th>
       <th>In Stock</th>
     </tr>
    </thead>
    <tbody>
      <% @items.each do |item|  %>
        <tr>
          <td><%= link_to item.title, item_path(item.id) %></td>
          <td><%= number_to_currency(item.cost) %></td>
          <td><%= item.inventory %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

 <%= will_paginate @items %>

app/views/items/show.html.erb
<table class="table table-hover for-yield">
  <thead>
  <tr>
    <th>Item</th>
    <th>Price</th>
    <th>Description</th>
    <th>In Stock</th>
  </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @item.title %></td>
      <td><%="$ #{@item.cost}" %></td>
      <td><%= @item.description %></td>
      <td><%= @item.inventory %></td>
      <td><%= button_to "Add Item", new_order_path(item_id: @item.id, quantity: 1), class: 'btn btn-default' %></td>
    </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Congo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Berkshire+Swash' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <% user = current_user if current_user %>
  <% admin = user[:admin] if current_user %>
  <%= react_component ('NavChoice'), {admin: admin} %>

  <%= render partial: 'shared/header' %>

  <p style='color:red;'><%= flash[:alert] %></p>
  <p style='color:green;'><%= flash[:notice] %></p>

  <div class="container">
    <div class="row">
      <div class="col-sm-8">
        <%= yield %>
      </div>
      <div class="col-sm-4 sidebar">
        <% if session[:user_id] %>
            <% cart = get_cart %>
            <% user = User.find(session[:user_id]) %>
            <%= render partial: 'shared/cart', locals: {name: user.name.capitalize, cart: cart} %>
        <% else %>
            <%= render partial: 'shared/login', locals: { new_user: new_user } %>
        <% end %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/orders/index.html.erb
<div class="for-yield">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Order #</th>
          <th>Customer</th>
          <th>Status</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order.id, order_path(order.id) %></td>
          <td><%= order.user.name %></td>
          <td><%= order.completed ? "Paid" : "Not Paid" %></td>
          <td><%= number_to_currency(order.order_items.total_due(order.id)) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
</div>
<%= will_paginate @orders %>

app/views/orders/show.html.erb
    <table class="table table-hover for-yield">
      <thead>
      <tr>
        <td>Items</td>
        <td>Description</td>
        <td>Cost</td>
      </tr>
      </thead>
      <tbody>
      <% @order.items.each do |item| %>
        <tr>
          <td><%= item.title %></td>
          <td><%= item.description %></td>
          <td><%= number_to_currency(item.cost) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

app/views/shared/_cart.html.erb
<div class="for-yield cart">
  <p><%= "Welcome #{name}" %></p>
    <% if cart %>
      <p><strong>Shopping Cart Total</strong>
        <%= number_to_currency(cart.order_items.total_due(cart.id)) %>
      </p>
      <ul>
        <% cart.items.each do |item| %>
          <li><%= item.title %></li>
            <ul><li><%= number_to_currency(item.cost) %>
                <%= button_to "Remove", "/orders/#{item.id}", method: 'delete', action: 'delete', class: 'btn btn-default btn-xs' %></li></ul><br>
        <% end %>
      </ul>
      <div class="checkout-box">
        <%= button_to "Check Out", checkout_path, class: 'btn btn-default'  %>
      </div>
    </div>
    <% else %>
    <p>Shop the World</p>
    <% end %>

app/views/shared/_header.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <header>
        <a href="/"><span class="glyphicon glyphicon-globe"></span>
        <span>Congo</span></a>
      </header>
    </div>
  </div>
</div>

app/views/shared/_login.html.erb
<section>
  <div class="sign-up">
    <p><strong>Sign Up Today</strong></p>
    <%= form_for(new_user) do |f| %>
        <%= label_tag(:name, "Name:") %>
        <p><%= f.text_field :name, class: "input" %></p>
        <%= label_tag(:email, "Email:") %>
        <p><%= f.text_field :email, class: "input" %></p>
        <%= label_tag(:password, "Password:") %>
        <p><%= f.password_field :password, class: "input" %></p>
        <%= label_tag(:password_confirmation, "Confirm Password:") %>
        <p><%= f.password_field :password_confirmation, class: "input" %></p>
        <%= f.submit "Submit", class: "btn btn-default" %>
    <% end %>
  </div>
</section>

app/views/users/index.html.erb
<div class="container for-yield" %>
  <div class="row">
    <div class="col-sm-12">
        <% @users.each do |user|  %>
            <%= user.name %>
        <% end %>
    </div>
  </div>
</div